//
// AssignUserMedicineRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AssignUserMedicineRequestDTO: Codable {

    public var medicineId: String
    public var repeatDaily: Int?
    public var repeatDay: Int?

    public init(medicineId: String, repeatDaily: Int?, repeatDay: Int?) {
        self.medicineId = medicineId
        self.repeatDaily = repeatDaily
        self.repeatDay = repeatDay
    }


}

