//
// CommonResponseOfUserDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CommonResponseOfUserDTO: Codable {

    public var code: Int
    public var data: UserDTO?
    public var error: String?

    public init(code: Int, data: UserDTO?, error: String?) {
        self.code = code
        self.data = data
        self.error = error
    }


}

