//
// CreateMedicineRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateMedicineRequestDTO: Codable {

    public var brand: String
    public var _description: String
    public var gramaj: String
    public var imagePath: String
    public var name: String
    public var skt: String

    public init(brand: String, _description: String, gramaj: String, imagePath: String, name: String, skt: String) {
        self.brand = brand
        self._description = _description
        self.gramaj = gramaj
        self.imagePath = imagePath
        self.name = name
        self.skt = skt
    }

    public enum CodingKeys: String, CodingKey { 
        case brand
        case _description = "description"
        case gramaj
        case imagePath
        case name
        case skt
    }


}

