//
// LogData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LogData: Codable {

    public var date: String
    public var _id: String?
    public var medicineDAO: MedicineDAO
    public var userName: String

    public init(date: String, _id: String?, medicineDAO: MedicineDAO, userName: String) {
        self.date = date
        self._id = _id
        self.medicineDAO = medicineDAO
        self.userName = userName
    }

    public enum CodingKeys: String, CodingKey { 
        case date
        case _id = "id"
        case medicineDAO
        case userName
    }


}

