//
// MedicineDAO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MedicineDAO: Codable {

    public var brand: String
    public var _description: String
    public var gramaj: String
    public var _id: String?
    public var name: String?
    public var photoPath: String
    public var skt: String

    public init(brand: String, _description: String, gramaj: String, _id: String?, name: String?, photoPath: String, skt: String) {
        self.brand = brand
        self._description = _description
        self.gramaj = gramaj
        self._id = _id
        self.name = name
        self.photoPath = photoPath
        self.skt = skt
    }

    public enum CodingKeys: String, CodingKey { 
        case brand
        case _description = "description"
        case gramaj
        case _id = "id"
        case name
        case photoPath
        case skt
    }


}

