//
// RegisterRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegisterRequestDTO: Codable {

    public enum Sex: String, Codable { 
        case erkek = "ERKEK"
        case kadin = "KADIN"
    }
    public enum ModelType: String, Codable { 
        case admin = "ADMIN"
        case doctor = "DOCTOR"
        case normal = "NORMAL"
    }
    public var age: Int?
    public var email: String?
    public var name: String?
    public var password: String?
    public var sex: Sex?
    public var surname: String?
    public var type: ModelType?
    public var weight: Double?

    public init(age: Int?, email: String?, name: String?, password: String?, sex: Sex?, surname: String?, type: ModelType?, weight: Double?) {
        self.age = age
        self.email = email
        self.name = name
        self.password = password
        self.sex = sex
        self.surname = surname
        self.type = type
        self.weight = weight
    }


}

