//
// UserMedicineDAO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserMedicineDAO: Codable {

    public var _id: String?
    public var medicineDAO: MedicineDAO
    public var repeatDaily: Int
    public var repeatDay: Int
    public var userId: String

    public init(_id: String?, medicineDAO: MedicineDAO, repeatDaily: Int, repeatDay: Int, userId: String) {
        self._id = _id
        self.medicineDAO = medicineDAO
        self.repeatDaily = repeatDaily
        self.repeatDay = repeatDay
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case medicineDAO
        case repeatDaily
        case repeatDay
        case userId
    }


}

