//
// UserDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserDTO: Codable {

    public enum ModelType: String, Codable { 
        case admin = "ADMIN"
        case doctor = "DOCTOR"
        case normal = "NORMAL"
    }
    public var age: Int
    public var authorizationKey: String
    public var email: String?
    public var _id: String
    public var name: String
    public var sex: String
    public var surname: String
    public var type: ModelType

    public init(age: Int, authorizationKey: String, email: String?, _id: String, name: String, sex: String, surname: String, type: ModelType) {
        self.age = age
        self.authorizationKey = authorizationKey
        self.email = email
        self._id = _id
        self.name = name
        self.sex = sex
        self.surname = surname
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case age
        case authorizationKey
        case email
        case _id = "id"
        case name
        case sex
        case surname
        case type
    }


}

