//
// MedicineControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class MedicineControllerAPI {
    /**
     addMedicine
     
     - parameter createMedicineRequestDTO: (body) createMedicineRequestDTO 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addMedicineUsingPOST(createMedicineRequestDTO: CreateMedicineRequestDTO, completion: @escaping ((_ data: CommonResponseOfboolean?,_ error: Error?) -> Void)) {
        addMedicineUsingPOSTWithRequestBuilder(createMedicineRequestDTO: createMedicineRequestDTO).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     addMedicine
     - POST /medicines
     - API Key:
       - type: apiKey Authorization 
       - name: JWT
     - examples: [{output=none}]
     
     - parameter createMedicineRequestDTO: (body) createMedicineRequestDTO 

     - returns: RequestBuilder<CommonResponseOfboolean> 
     */
    open class func addMedicineUsingPOSTWithRequestBuilder(createMedicineRequestDTO: CreateMedicineRequestDTO) -> RequestBuilder<CommonResponseOfboolean> {
        let path = "/medicines"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createMedicineRequestDTO)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<CommonResponseOfboolean>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     getMedicines
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMedicinesUsingGET(completion: @escaping ((_ data: CommonResponseOfListOfMedicineDAO?,_ error: Error?) -> Void)) {
        getMedicinesUsingGETWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     getMedicines
     - GET /medicines
     - API Key:
       - type: apiKey Authorization 
       - name: JWT
     - examples: [{output=none}]

     - returns: RequestBuilder<CommonResponseOfListOfMedicineDAO> 
     */
    open class func getMedicinesUsingGETWithRequestBuilder() -> RequestBuilder<CommonResponseOfListOfMedicineDAO> {
        let path = "/medicines"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<CommonResponseOfListOfMedicineDAO>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
